### ISSUE TITLE
What do these tflite mean?

### ISSUE THREAD

**Issue by lmy931** [MrinaliniU/Human-Activity-Recognition#2]
Hi! I saw many .tflite in your asset folder. From the code I know the "humanposemodel.tflite" is used for predicting human pose, but how about other tflite files?
I am seeking a good tflite that can detect human body coordinates. I'm doing some research on HAR as well. I can show you some video demo about my project. My Gmail address is aumengyu@gmail.com. My name is Lee.

**Comment by MrinaliniU** [comment]
Hi Lee, 

The other tflite files are for human action prediction. My personal email ID is mrinaliniu88@gmail.com. You can send specific questions about the project there.
